name: Go

on:
  - push
  - pull_request

jobs:

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v -x ./...

    - name: Test
      run: go test -v ./...

  build-macos:
    name: Build on Darwin
    runs-on: macos-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
